.SUFFIXES:

ifeq ($(strip $(DEVKITPPC)),)
$(error "Please set DEVKITPPC in your environment. export DEVKITPPC=<path to>devkitPPC")
endif

include $(DEVKITPPC)/wii_rules

TARGET		:=	boot
BUILD		:=	build
SOURCES		:=	source \
				source/engine/wii	\
				source/engine/gc	\
				source/engine	\
				source/engine/general	\
				source/engine/lib/png	\
				source/scenes	\
				source/objects	\
				source/tiles	\
				source/effects	\
				source/scripts	\
				source/platform/wii	\
				source/platform/gc
				
DATA		:=	assets assets/audio assets/graphics
TEXTURES	:=	textures
INCLUDES	:=	source

CFLAGS		=	-g -O2 -Wall $(MACHDEP) $(INCLUDE)
CFLAGS      += -DCURRENT_PLATFORM=PLATFORM_$(PLATFORM)
CXXFLAGS	=	$(CFLAGS)
LDFLAGS		=	-g $(MACHDEP) -Wl,-Map,$(notdir $@).map


LIBS := -lfat
LIBS += -lwiiuse -lwupc -lbte
LIBS += -lvorbisidec -logg -lasnd
LIBS += -logc -lm
LIBS += -lwiikeyboard
LIBDIRS := $(PORTLIBS) $(CURDIR)/source/engine/lib/wupc

ifneq ($(BUILD),$(notdir $(CURDIR)))

export OUTPUT	:=	$(CURDIR)/dist/wii/$(TARGET)
export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
					$(foreach dir,$(DATA),$(CURDIR)/$(dir)) \
					$(foreach dir,$(TEXTURES),$(CURDIR)/$(dir))
export DEPSDIR	:=	$(CURDIR)/$(BUILD)

CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
sFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
SFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.S)))
BINFILES	:=	$(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))
SCFFILES	:=	$(foreach dir,$(TEXTURES),$(notdir $(wildcard $(dir)/*.scf)))
TPLFILES	:=	$(SCFFILES:.scf=.tpl)

ifeq ($(strip $(CPPFILES)),)
	export LD	:=	$(CC)
else
	export LD	:=	$(CXX)
endif

export OFILES_BIN		:=	$(addsuffix .o,$(BINFILES)) $(addsuffix .o,$(TPLFILES))
export OFILES_SOURCES	:=	$(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(sFILES:.s=.o) $(SFILES:.S=.o)
export OFILES			:=	$(OFILES_BIN) $(OFILES_SOURCES)
export HFILES			:=	$(addsuffix .h,$(subst .,_,$(BINFILES))) $(addsuffix .h,$(subst .,_,$(TPLFILES)))

export INCLUDE	:=	$(foreach dir,$(INCLUDES),-iquote $(CURDIR)/$(dir)) \
					$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
					-I$(CURDIR)/$(BUILD) \
					-I$(LIBOGC_INC)

export LIBPATHS	:= -L$(LIBOGC_LIB) $(foreach dir,$(LIBDIRS),-L$(dir)/lib)

.PHONY: $(BUILD) clean distclean

ifeq (,$(wildcard $(DEVKITPRO)/portlibs/ppc/include/tremor/ivorbiscodec.h))
$(BUILD):
	@echo "*---------------------------------------------------------*"
	@echo "Please install libvorbisidec:"
	@echo "(dkp-)pacman -S ppc-libvorbisidec"
	@echo "*---------------------------------------------------------*"
else
$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@mkdir -p $(CURDIR)/dist/wii
	@echo "CFLAGS: $(CFLAGS)"
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.WII PLATFORM=$(PLATFORM)
endif
clean:
	@echo clean ...
	@rm -fr $(BUILD)

distclean:
	@echo distclean ...
	@rm -f $(CURDIR)/dist/wii/$(TARGET).elf
	@rm -f $(CURDIR)/dist/wii/$(TARGET).dol

run:
	wiiload $(CURDIR)/dist/wii/$(TARGET).dol

else

DEPENDS	:=	$(OFILES:.o=.d)

$(OUTPUT).dol: $(OUTPUT).elf
$(OUTPUT).elf: $(OFILES)
$(OFILES_SOURCES) : $(HFILES)

%.jpg.o	:	%.jpg
	@echo $(notdir $<)
	$(bin2o)

%.png.o	:	%.png
	@echo $(notdir $<)
	$(bin2o)

%.tpl.o	%_tpl.h :	%.tpl
	@echo $(notdir $<)
	@$(bin2o)

%.ogg.o	%_ogg.h :	%.ogg
	@echo $(notdir $<)
	$(bin2o)

%.bin.o : %.bin
	@echo $(notdir $<)
	$(bin2o)

%.room.o : %.room
	@echo $(notdir $<)
	$(bin2o)

%.acs.o %_acs.h : %.acs
	@echo $(notdir $<)
	@$(bin2o)
	
	
-include $(DEPENDS)

endif